IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'talentorg' AND TABLE_NAME = 'T_APP_CONFIGURATION')
CREATE TABLE T_APP_CONFIGURATION(	
	GROUP_NAME VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	VALUE VARCHAR(255) NOT NULL,
	PRIMARY KEY(GROUP_NAME, NAME)
);
